# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/andrew/Documents/proyecto-Digitales/formaLenta/pixelRadiation/pixelRadiation.srcs/sources_1/ip/fix2float/fix2float.xci
# IP: The module: 'fix2float' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/andrew/Documents/proyecto-Digitales/formaLenta/pixelRadiation/pixelRadiation.srcs/sources_1/ip/fix2float/fix2float_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fix2float'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/andrew/Documents/proyecto-Digitales/formaLenta/pixelRadiation/pixelRadiation.srcs/sources_1/ip/fix2float/fix2float.xci
# IP: The module: 'fix2float' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/andrew/Documents/proyecto-Digitales/formaLenta/pixelRadiation/pixelRadiation.srcs/sources_1/ip/fix2float/fix2float_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fix2float'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
