webtalk_init -webtalk_dir /home/andrew/Documents/ProyectoFinalAndrewMorrison/pixelRadiation/pixelRadiation.sim/sim_1/behav/xsim.dir/tb_pixelRadiation_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jun 14 20:04:46 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1733598" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6901d3b176835e3ebd08c7c73f8cf34b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e8702303d22d465db3e367021ada9c08" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "34" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 1700X Eight-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1841.718 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "189431 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "6.87_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "159932_KB" -context "xsim\\usage"
webtalk_transmit -clientid 192793937 -regid "" -xml /home/andrew/Documents/ProyectoFinalAndrewMorrison/pixelRadiation/pixelRadiation.sim/sim_1/behav/xsim.dir/tb_pixelRadiation_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/andrew/Documents/ProyectoFinalAndrewMorrison/pixelRadiation/pixelRadiation.sim/sim_1/behav/xsim.dir/tb_pixelRadiation_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/andrew/Documents/ProyectoFinalAndrewMorrison/pixelRadiation/pixelRadiation.sim/sim_1/behav/xsim.dir/tb_pixelRadiation_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
